# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # JJGR: Change back to main from cicd
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Matrix strategy from
    # https://github.com/msys2/MINGW-packages/blob/master/.github/workflows/main.yml
    strategy:
      matrix:
        include: [{ msystem: MINGW64, arch: x86_64 }]

    defaults:
      run:
        shell: cmd

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: See free space
        run: powershell -Command Get-PSDrive

      # This is the shortest job, but in this case it pulls all MSYS/MINGW64
      - name: Collect dependencies
        run: .\emacs-build.cmd --clone --branch feature/native-comp

      - name: See free space
        run: powershell -Command Get-PSDrive

      # Now download dependencies
      - name: Show we can write text
        run: .\emacs-build.cmd --deps --branch feature/native-comp

      - name: See free space
        run: powershell -Command Get-PSDrive

      # Build an pack
      - name: Show we can write text
        run: .\emacs-build.cmd --build --pack-emacs --branch feature/native-comp

      - name: See free space
        run: powershell -Command Get-PSDrive

      # Full emacs
      - name: Clone emacs
        run: .\emacs-build.cmd --pack-all --hunspell --branch feature/native-comp

      - name: See free space
        run: powershell -Command Get-PSDrive

      # Upload everything
      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.msystem }}-packages
          path: zips/*
